### PR TITLE
Create pl_pl.json

### PR DESCRIPTION
**Pull request by CrazyBarkley**

### CODE REVIEW

**Comment by QinomeD** [comment]
I would change a few things:
- "Czernitowa kuchenka" instead of "Czernitowy Stove"
- "Mimigoździk" or "Mimikarnacja" instead of "Mimicarnation"
- two e's in "Talerz faszerowaneej pieczeni hoglina" and in "Netherowa ceeglana wędzarka"
- "Kawałek magmołaza" instead of "Plasterek magmołaza"
- "grilowany" is written with two l's -> "grillowany"
- "Synteza" or simply "Rozkład" instead of "Skład" - Rozkład means decomposition, not composition, but "Skład" sucks imo.

I can fix it if you would give me [allow edits from maintainers](https://github.blog/2016-09-07-improving-collaboration-with-forks/)

**Comment by CrazyBarkley** [comment]
Thank you for this insight! those indeed sound better. I already switched allow edits by maintainers on. You can make improvements now :D

btw "Mimigoździk" sounds a lot better than "Mimikarnacja" IMO.

I'm still learning GitHub, if allow edits will not work or sth let me know!

**Comment by QinomeD** [comment]
Yeah, did the cool goździk

**Comment by CrazyBarkley** [comment]
R u polish by any chance? I can't imagine anyone seeing those errors and correct them without being polish XD

**Comment by QinomeD** [comment]
> R u polish by any chance? I can't imagine anyone seeing those errors and correct them without being polish XD

I am

**Comment by CrazyBarkley** [comment]
W takim razie szalom XDD Świetny pomysł na moda swoją drogą 😄

**Comment by QinomeD** [comment]
To nie mój mod, dołączyłem tutaj niedawno raczej. Mam swojego, niedokońcoznego, moda, o którym wie niewiele osób - jak jesteś na serwerze dsc Chef's Delights, to mogę coś wysłać wsm, bo czemu nie.

For non-polish people watching this - dw I didn't say anything illegal xd

**Comment by CrazyBarkley** [comment]
Aaa widzisz, ciąglę się uczę jak GitHub działa. Pewnie! Czemu nie :D Z chęcią zobaczę.

**Pull request merged**
